### ISSUE TITLE
Unable to load dtracker.so file

### ISSUE THREAD

**Issue by vivek425ster** [m000/dtracker#1]
After successfully building dtracker it is showing me the following error. E:Unable to load /home/vivek/libdft/dtracker/./obj-ia32/dtracker.so: /home/vivek/libdft/dtracker/./obj-ia32/dtracker.so: undefined symbol: _ZN15LEVEL_PINCLIENT13TRACE_VersionEPNS_11TRACE_CLASSE

**Comment by m000** [comment]
That should be easy to fix. Edit the makefile. In the linking recipe, move
the tool libraries at the end of the command (_after_ -ldft).

Don't forget to make a pull request if that worked :)

**Comment by vivek425ster** [comment]
@m000  Thanks It worked. I have sent a PR.
