### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [m000/dtracker#6]
I would like to point out that identifiers like “[`__DTRACKER_H__`](https://github.com/m000/dtracker/blob/d75fae716dd36b7afbfa3ab62b818d4cac41b4f0/dtracker.H#L1 "Update candidate")” and “[`__HOOKS_H__`](https://github.com/m000/dtracker/blob/7fd9ca063c40969a47b9c8fdf0be25b1eb7da147/hooks/hooks.H#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/m000/dtracker/commit/81dad620c971704bb19259b92302ce7bbf38061d "Renaming of include guards").

**Comment by elfring** [comment]
Are there [a few update candidates left over](https://github.com/m000/dtracker/blob/652e6c47f8ef6d1736ccc6bfe56b5b9750a797de/osutils.H#L5 "More renaming of identifiers?")?

**Comment by m000** [comment]
Indeed. Fixed the remaining. Will also fix the libdft code in the following days.
